version: '3.8'

services:
    db:
      image: postgres:16-alpine
      container_name: db
      restart: always
      volumes:
        - data_value:/var/lib/postgresql/data/
      environment:
        LANG: "ru_RU.UTF-8"
        POSTGRES_INITDB_ARGS: '--locale-provider=icu --icu-locale=ru-RU'
      expose:
        - "5432"
      env_file:
        - ../.env


    backend:
      build:
        context: ..
        dockerfile: Dockerfile
      container_name: backend
      command: bash -c "cd backend/ && gunicorn backend.wsgi:application --bind 0:8000"
      restart: always
      volumes:
        - static_value:/app/backend/static/
        - media_value:/app/backend/media/
        - ../.data/logs/:/app/.data/logs/
      expose:
        - "8000"
      env_file:
        - ../.env
      depends_on:
        - db
      image: you_can_bot:latest

    bot:
      build:
        context: ..
        dockerfile: Dockerfile
      container_name: bot
      command: bash -c "cd bot/ && python run_bot.py"
      env_file:
        - ../.env
      restart: always
      volumes:
        - ../.data/logs/:/app/.data/logs/
      depends_on:
        - backend
      image: you_can_bot:latest

    nginx:
      image: nginx:1.24-alpine
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - static_value:/var/html/static/
        - media_value:/var/html/media/
      depends_on:
        - bot


volumes:
    static_value:
    media_value:
    data_value:
