version: '3.8'

services:
    db:
      image: postgres:15.0-alpine
      volumes:
        - /var/lib/postgresql/data/
      env_file:
        - ../.env

    backend:
      build:
        context: ..
        dockerfile: Dockerfile
      container_name: backend
      command: bash -c "cd backend/ && gunicorn backend.wsgi:application --bind 0:8000"
      restart: always
      volumes:
        - static_value:/app/backend/static/
        - media_value:/app/media/
        - ../.data/logs/:/app/.data/logs/
      env_file:
        - ../.env
      depends_on:
        - db

    bot:
      build:
        context: ..
        dockerfile: Dockerfile
      container_name: bot
      command: bash -c "cd bot/ && python run_bot.py"
      env_file:
        - ../.env
      restart: always
      volumes:
        - ../.data/logs/:/app/.data/logs/
      depends_on:
        - backend

    nginx:
      image: nginx:1.21.3-alpine

      ports:
        - "80:80"

      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - static_value:/var/html/static/
        - media_value:/var/html/media/

      depends_on:
        - bot


volumes:
    static_value:
    media_value:
    data_value:
