version: '3.8'

services:
    db:
      image: postgres:16
      container_name: db
      restart: always
      volumes:
        - db_data:/var/lib/postgresql/data/
      environment:
        LANG: ru_RU.UTF-8
        POSTGRES_INITDB_ARGS: '--locale-provider=icu --icu-locale=ru-RU'
      ports:
        - "5432:5432"
      env_file:
        - ../.env

    backend:
      image: ghcr.io/studio-yandex-practicum/you_can_bot:latest
      container_name: backend
      command: bash -c "cd backend/ && gunicorn backend.wsgi:application --bind 0:8000"
      restart: always
      volumes:
        - static_value:/app/backend/static/
        - media_value:/app/media/
        - ../.data/logs/:/app/.data/logs/
      env_file:
        - ../.env
      depends_on:
        - db

    bot:
      image: ghcr.io/studio-yandex-practicum/you_can_bot:latest
      container_name: bot
      command: bash -c "cd bot/ && python run_bot.py"
      env_file:
        - ../.env
      restart: always
      volumes:
        - ../.data/logs/:/app/.data/logs/
      depends_on:
        - backend

    nginx:
      image: nginx:1.21.3-alpine

      ports:
        - "80:80"
        - "443:443"

      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - static_value:/var/html/static/
        - media_value:/var/html/media/

      depends_on:
        - bot
        - backend


volumes:
    static_value:
    media_value:
    data_value:
