# Generated by Django 4.2.4 on 2023-08-15 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Введите номер ответа", verbose_name="Номер ответа"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите содержание ответа",
                        verbose_name="Содержание ответа",
                    ),
                ),
            ],
            options={
                "verbose_name": "ответ",
                "verbose_name_plural": "3. Ответы на задания",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Введите вопрос", verbose_name="Содержание вопроса"
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        help_text="Введите варианты ответа",
                        verbose_name="Варианты ответа",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "вопрос",
                "verbose_name_plural": "4. Вопросы",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Введите номер задания", verbose_name="Номер задания"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Введите расшифровку", verbose_name="Расшифровка"
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(
                        default=False, verbose_name="Статус выполнения"
                    ),
                ),
                (
                    "pass_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата выполнения"
                    ),
                ),
                (
                    "answers",
                    models.ForeignKey(
                        help_text="Укажите ответы",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_status",
                        to="api.answer",
                        verbose_name="Ответы",
                    ),
                ),
            ],
            options={
                "verbose_name": "статус",
                "verbose_name_plural": "2. Статусы заданий",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="UserFromTelegram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.IntegerField(verbose_name="Telegram ID")),
                ("name", models.CharField(max_length=150, verbose_name="Имя")),
                ("surname", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("mentor", models.CharField(max_length=150, verbose_name="Ментор")),
                (
                    "questions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_user",
                        to="api.question",
                        verbose_name="Пользователь Телеграма",
                    ),
                ),
                (
                    "tasks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_user",
                        to="api.taskstatus",
                        verbose_name="Пользователь Телеграма",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователя",
                "verbose_name_plural": "1. Пользователи из Телеграмма",
                "ordering": ("pk",),
            },
        ),
    ]
