# Generated by Django 4.2.4 on 2023-08-21 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("task", "number")},
        ),
    ]
