# Generated by Django 4.2.4 on 2023-08-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfromtelegram",
            name="telegram_id",
            field=models.IntegerField(unique=True, verbose_name="Telegram ID"),
        ),
    ]
