# Generated by Django 4.2.4 on 2023-09-04 08:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_answer_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Задание 1"),
                            (2, "Задание 2"),
                            (3, "Задание 3"),
                            (4, "Задание 4"),
                            (5, "Задание 5"),
                            (6, "Задание 6"),
                            (7, "Задание 7"),
                            (8, "Задание 8"),
                        ],
                        primary_key=True,
                        serialize=False,
                        verbose_name="Номер задания",
                    ),
                ),
                (
                    "end_question",
                    models.PositiveSmallIntegerField(
                        verbose_name="Последний номер задания"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=1)
                        ],
                        verbose_name="Номер вопроса",
                    ),
                ),
                ("content", models.TextField()),
                ("example", models.TextField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.task",
                        verbose_name="Задание",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="api.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="taskstatus",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.question",
                verbose_name="Вопрос",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskstatus",
            name="task",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.task",
                verbose_name="Задание",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("task", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="taskstatus",
            unique_together={("user", "task")},
        ),
        migrations.RemoveField(
            model_name="answer",
            name="number",
        ),
        migrations.RemoveField(
            model_name="taskstatus",
            name="end_question",
        ),
        migrations.RemoveField(
            model_name="taskstatus",
            name="number",
        ),
    ]
