# Generated by Django 4.2.4 on 2023-08-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_userfromtelegram_telegram_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfromtelegram",
            options={
                "ordering": ("pk",),
                "verbose_name": "пользователя",
                "verbose_name_plural": "1. Пользователи из Телеграма",
            },
        ),
        migrations.AlterField(
            model_name="answer",
            name="content",
            field=models.CharField(
                help_text="Введите содержание ответа",
                max_length=10,
                verbose_name="Содержание ответа",
            ),
        ),
        migrations.AlterField(
            model_name="userfromtelegram",
            name="questions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_user",
                to="api.question",
                verbose_name="Ответы пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="userfromtelegram",
            name="tasks",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_user",
                to="api.taskstatus",
                verbose_name="Пройденные задания",
            ),
        ),
    ]
