# Generated by Django 4.2.4 on 2023-09-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_questions_in_database"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="answer",
            field=models.TextField(default="", verbose_name="Ответ психолога"),
        ),
        migrations.AlterField(
            model_name="taskstatus",
            name="summary",
            field=models.TextField(default="", verbose_name="Расшифровка"),
        ),
        migrations.AlterField(
            model_name="userfromtelegram",
            name="telegram_username",
            field=models.CharField(max_length=32, verbose_name="Никнейм Telegram"),
        ),
    ]
