# Generated by Django 4.2.4 on 2023-09-04 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_non_unique_telegram_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="task",
            new_name="task_status",
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together=set(),
        ),
    ]
