# Generated by Django 4.2.4 on 2023-09-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_task_answer_task_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="question",
            name="example",
            field=models.TextField(default=""),
        ),
    ]
