# Generated by Django 4.2.4 on 2023-09-05 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_add_results_to_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="answer",
            field=models.TextField(
                blank=True, default="", verbose_name="Ответ психолога"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="example",
            field=models.TextField(
                blank=True, default="", verbose_name="Пример ответа"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="photo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question",
                to="api.photo",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="taskstatus",
            name="pass_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                verbose_name="Дата выполнения",
            ),
        ),
    ]
