# Generated by Django 4.2.5 on 2023-09-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_choice_description_alter_problem_answer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Вопрос", "verbose_name_plural": "Вопросы"},
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("task", "number"), name="unique_task_question_number"
            ),
        ),
    ]
