# Generated by Django 4.2.5 on 2023-10-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_replace_key_with_textfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentorprofile",
            name="telegram_username",
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="telegram_id",
            field=models.IntegerField(
                blank=True,
                help_text="На этот id в Telegram могут быть отправлены уведомления",
                null=True,
                unique=True,
                verbose_name="Никнейм Telegram",
            ),
        ),
    ]
