# Generated by Django 4.2.5 on 2023-10-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_mentorprofile_options_alter_problem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorprofile",
            name="telegram_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="На этот id в Telegram могут быть отправлены уведомления",
                null=True,
                verbose_name="Айди Telegram",
            ),
        ),
    ]
