# Generated by Django 4.2.5 on 2023-11-09 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0014_alter_mentorprofile_telegram_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resultstatus",
            options={
                "verbose_name": "Результат пользователя",
                "verbose_name_plural": "Результаты пользователя",
            },
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="telegram_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="На этот id в Telegram могут быть отправлены уведомления",
                null=True,
                unique=True,
                verbose_name="Айди Telegram",
            ),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
