# Generated by Django 4.2.5 on 2023-11-08 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_mentorprofile_telegram_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"verbose_name": "Картинка", "verbose_name_plural": "Картинки"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ("number",),
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.AlterModelOptions(
            name="resultstatus",
            options={
                "verbose_name": "Результат пользователя",
                "verbose_name_plural": "Результаты пользователя",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("number",),
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
            },
        ),
    ]
