# Generated by Django 4.2.5 on 2023-11-10 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0015_alter_resultstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentorprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
