# Generated by Django 4.2.5 on 2023-11-21 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_mentorprofile_telegram_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"ordering": ("pk",)},
        ),
    ]
