# Generated by Django 4.2.5 on 2023-12-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_choice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mentorprofile",
            options={
                "verbose_name": "Профиль профдизайнера",
                "verbose_name_plural": "Профили профдизайнеров",
            },
        ),
        migrations.AlterModelOptions(
            name="resultstatus",
            options={
                "ordering": ("top",),
                "verbose_name": "Результат пользователя",
                "verbose_name_plural": "Результаты пользователя",
            },
        ),
        migrations.AlterField(
            model_name="problem",
            name="answer",
            field=models.TextField(default="", verbose_name="Ответ профдизайнера"),
        ),
        migrations.AlterField(
            model_name="taskstatus",
            name="is_done",
            field=models.BooleanField(
                default=False,
                help_text="Чтобы сбросить выполнение задания и дать подростку пройти его заново, уберите здесь галочку. Также выставите в поле 'Текущий вопрос' значение 0.",
                verbose_name="Выполнено",
            ),
        ),
        migrations.AlterField(
            model_name="userfromtelegram",
            name="mentor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.mentorprofile",
                verbose_name="Профдизайнер",
            ),
        ),
    ]
