# Generated by Django 4.2.5 on 2024-03-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_answer_field_in_problem_is_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.TextField(
                blank=True, default="", verbose_name="Название задания"
            ),
        ),
    ]
