# Generated by Django 4.2.13 on 2024-09-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfromtelegram",
            name="telegram_username",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Никнейм Telegram"
            ),
        ),
    ]
