# Generated by Django 4.2.5 on 2024-02-29 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("number",),
                "verbose_name": "Задание",
                "verbose_name_plural": "Заданий",
            },
        ),
    ]
