# Generated by Django 4.2.13 on 2024-10-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_alter_userfromtelegram_telegram_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfromtelegram",
            options={
                "ordering": ("-last_task_completed_at",),
                "verbose_name": "пользователя",
                "verbose_name_plural": "Пользователи из Telegram",
            },
        ),
        migrations.AddField(
            model_name="userfromtelegram",
            name="last_task_completed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Последнее задание выполнено",
            ),
        ),
        migrations.AddField(
            model_name="userfromtelegram",
            name="tasks_completed_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Выполненных заданий"
            ),
        ),
    ]
