# Generated by Django 4.2.22 on 2025-06-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_userfromtelegram_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfromtelegram",
            name="test_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Итоговая расшифровка теста для отображения в PDF",
                verbose_name="Расшифровка от профдизайнера",
            ),
        ),
    ]
