# Generated by Django 4.2.5 on 2024-03-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_alter_task_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.TextField(
                blank=True, default="", verbose_name="Название задания"
            ),
        ),
    ]
