name: Django tests

on:
  push:
  pull_request:
    branches: [develop]

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      SECRET_KEY: test-key-not-good
      DB_PORT: 5432
      DB_HOST: localhost
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    -
      name: Check out the repo
      uses: actions/checkout@v3
    -
      name: Setup Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: "1.5.1"
    -
      name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    -
      name: Install dependencies
      run: |
        poetry install
        poetry run pip install psycopg2-binary
    -
      name: Django tests
      env:
        DEBUG: "0"
        SECRET_KEY: ${{ env.SECRET_KEY }}
        POSTGRES_USER: ${{ env.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        DB_HOST: ${{ env.DB_HOST }}
        POSTGRES_DB: ${{ env.POSTGRES_DB }}
        DB_PORT: ${{ env.DB_PORT }}
      run: |
        poetry run python src/backend/manage.py test src/backend
