# .github/workflows/**main.yml**
name: Test flake8 and isort workflow

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    -
      name: Check out the repo
      uses: actions/checkout@v3
    - 
      name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - 
      name: Install Poetry
      uses: Gr1N/setup-poetry@v8

    - 
      name: Install dependencies
      run: |
        poetry install
    -
      name: Test with flake8
      run: |
        python -m flake8
    -
      name: Test with isort
      run: |
        python -m isort
