# .github/workflows/**main.yml**
name: Test flake8 and isort workflow

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    -
      name: Check out the repo
      uses: actions/checkout@v3
    - 
      name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    -
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return
        pip install black
        pip install isort
    -
      name: Test with flake8
      run: |
        python -m flake8
    -
      name: Test with isort
      run: |
        python -m isort
